name: Update IPTV Token
on:
  schedule:
    - cron: '*/30 * * * *' # Cứ 30 phút nó tự chạy 1 lần để đổi token
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python get_link.py
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sctv5.m3u
          git commit -m "Auto update token" || exit 0
          git push
