name: Update IPTV Token
on:
  schedule:
    - cron: '*/30 * * * *' # Tự động chạy mỗi 30 phút để đổi mã mới
  workflow_dispatch: # Cho phép bạn bấm nút chạy bằng tay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Lấy code từ kho của bạn

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Cài đặt môi trường Python

      - name: Install Selenium and Chrome
        run: |
          pip install selenium requests
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable # Cài trình duyệt Chrome để "giả lập" người dùng

      - name: Run script
        run: python get_link.py # Chạy file python để bốc link SCTV5

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sctv5.m3u
          git commit -m "Auto update token: $(date)" || exit 0
          git push origin main # Lưu file m3u mới vào kho
